const PROJECTS = [
  {
    id:    'gastro-brand',
    tags:  ['branding'],
    url:   '/projects/gastro-brand/',
    thumb: '/images/gastro-brand/thumb.webp',
    videoThumb: '/images/gastro-brand/thumb.mp4',
    trail: ['/images/gastro-brand/trail-1.webp'],
  },
  {
    id:    'gastro-app',
    tags:  ['product'],
    url:   '/projects/gastro-app/',
    thumb: '/images/gastro-app/thumb.webp',
    trail: ['/images/gastro-app/trail-1.webp'],
  },
  {
    id:    'alaz-brand',
    tags:  ['branding'],
    url:   '/projects/alaz-brand/',
    thumb: '/images/alaz-brand/thumb.webp',
    videoThumb: '/images/alaz-brand/thumb.mp4',
    trail: ['/images/alaz-brand/trail-1.webp'],
  },
  {
    id:    'alaz-product',
    tags:  ['product'],
    url:   '/projects/alaz-product/',
    thumb: '/images/alaz-product/thumb.webp',
    trail: ['/images/alaz-product/trail-1.webp'],
  },
  {
    id:    'kanto-brand',
    tags:  ['branding'],
    url:   '/projects/kanto-brand/',
    thumb: '/images/kanto-brand/thumb.png',
    trail: ['/images/kanto-brand/thumb.png'],
  },
  {
    id:    'kanto-product',
    tags:  ['product'],
    url:   '/projects/kanto-product/',
    thumb: '/images/kanto-product/thumb.png',
    trail: ['/images/kanto-product/thumb.png'],
  },
  {
    id:    'soul-tv',
    tags:  ['product'],
    url:   '/projects/soul-tv/',
    thumb: '/images/soul-tv/thumb.png',
    trail: ['/images/soul-tv/trail-1.webp'],
  },
  {
    id:    'peru-tourism',
    tags:  ['product'],
    url:   '/projects/peru-tourism/',
    thumb: '/images/peru-tourism/thumb.png',
    trail: ['/images/peru-tourism/thumb.png'],
  },
  {
    id:    'getaway-stays',
    tags:  ['product'],
    url:   '/projects/getaway-stays/',
    thumb: '/images/getaway-stays/thumb.png',
    trail: ['/images/getaway-stays/thumb.png'],
  },
  {
    id:    'viva-conexiones',
    tags:  ['product'],
    url:   '/projects/viva-conexiones/',
    thumb: '/images/viva-conexiones/thumb.png',
    trail: ['/images/viva-conexiones/thumb.png'],
  },
  {
    id:    'smart-doctor',
    tags:  ['product'],
    url:   '/projects/smart-doctor/',
    thumb: '/images/smart-doctor/thumb.png',
    trail: ['/images/smart-doctor/thumb.png'],
  },
  {
    id:    'rocasac',
    tags:  ['branding'],
    url:   '/projects/rocasac/',
    thumb: '/images/rocasac/thumb.png',
    trail: ['/images/rocasac/thumb.png'],
  },
  {
    id:    'freeda',
    tags:  ['branding'],
    url:   '/projects/freeda/',
    thumb: '/images/freeda/thumb.png',
    trail: ['/images/freeda/thumb.png'],
  },
  {
    id:    'ritrovo',
    tags:  ['branding'],
    url:   '/projects/ritrovo/',
    thumb: '/images/ritrovo/thumb.png',
    trail: ['/images/ritrovo/thumb.png'],
  },
  {
    id:    'mycelia',
    tags:  ['branding'],
    url:   '/projects/mycelia/',
    thumb: '/images/mycelia/thumb.png',
    trail: ['/images/mycelia/thumb.png'],
  },
  {
    id:    'linking-card',
    tags:  ['branding'],
    url:   '/projects/linking-card/',
    thumb: '/images/linking-card/thumb.png',
    trail: ['/images/linking-card/thumb.png'],
  },
];
